# This file is part of the MBOptimization package.
#
# (c) Michael Barbey <michael@mb-webdev.ch>
#
# Do not distribute this file or any part of this package without the official authorizazion of mb-webdev


services:
    mb.optimization.response.listener:
        class: MB\Bundle\OptimizationBundle\Listeners\HTTPResponseListener
        arguments: 
            - "%mb_optimization%"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: changeHeaders }
            - { name: kernel.event_listener, event: kernel.response, method: trimContent }
