services:
    mb.optimization.response.listener:
        class: MB\Bundle\OptimizationBundle\Listeners\HTTPResponseListener
        arguments: 
            - "%mb_optimization%"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: changeHeaders }
            - { name: kernel.event_listener, event: kernel.response, method: trimContent }
